Delete old file versions on IPFS

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -83,8 +83,6 @@ jobs:
           - name: Local Integration Testsing
             run: |
               make local-test
-          # IPFS_OLD_HASH=$(ipfs-api pinned saifu-transfer-www-$RELEASE_VER --key=$PINATA_API_JWT --verbose=true | tail -n 1 | bash-utils jsonParse "rows.[0].ipfs_pin_hash" || echo "") && \
-          #    [ ! -z "$IPFS_OLD_HASH" ] && ipfs-api delete $IPFS_OLD_HASH --key=$PINATA_API_JWT --verbose=true && echo "deleted: $IPFS_OLD_HASH"
           - name: Publishing Binaries
             shell: bash
             run: |
@@ -93,7 +91,9 @@ jobs:
               echo "INFO: Unpacking web app..."
               rm -rfv ./build/ipfs && mkdir -p ./build/ipfs && cd ./build/ipfs
               unzip ../../bin/ipfs-web-app.zip && ls -l ./ && cd ../../
-              ipfs-api pin ./build/ipfs saifu-transfer-www-$RELEASE_VER --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
+              IPFS_UPLOAD_NAME=saifu-transfer-www-$RELEASE_VER
+              ipfs-api delete $IPFS_UPLOAD_NAME --key=$PINATA_API_JWT --verbose=true || echo "WARNING: Failed to delete file with name '$IPFS_UPLOAD_NAME' request failed or it might not exist"
+              ipfs-api pin ./build/ipfs $IPFS_UPLOAD_NAME --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
               IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash")
               IPFS_HASH_SHORT=${IPFS_HASH::10}...${IPFS_HASH: -3}
               echo "$IPFS_HASH" > ./bin/ipfs-cid.txt
