do not throw ipfs pin immediately

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -90,7 +90,7 @@ jobs:
               echo "INFO: Unpacking web app..."
               rm -rfv ./build/ipfs && mkdir -p ./build/ipfs && cd ./build/ipfs
               unzip ../../bin/ipfs-web-app.zip && ls -l ./ && cd ../../
-              ipfs-api pin ./build/ipfs saifu-transfer-www-$RELEASE_VER --key=$PINATA_API_JWT &> ipfs-pin.log
+              ipfs-api pin ./build/ipfs saifu-transfer-www-$RELEASE_VER --key=$PINATA_API_JWT &> ipfs-pin.log || echo "ERROR: Failed to pin web app"
               cat ipfs-pin.log
               IPFS_HASH=$(cat ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".IpfsHash")
               echo "IPFS_HASH=$IPFS_HASH" >> ./bin/public-envs.sh
