hash fix & PR comments

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,7 +16,7 @@ jobs:
       id-token: write
       pull-requests: write
     container:
-      image: ghcr.io/kiracore/docker/base-image:v0.10.7
+      image: ghcr.io/kiracore/docker/base-image:v0.10.8
     steps:
           # Work around https://github.com/actions/checkout/issues/760
           - name: Add safe.directory
@@ -91,8 +91,8 @@ jobs:
               echo "INFO: Unpacking web app..."
               rm -rfv ./build/ipfs && mkdir -p ./build/ipfs && cd ./build/ipfs
               unzip ../../bin/ipfs-web-app.zip && ls -l ./ && cd ../../
-              ipfs-api pin ./build/ipfs saifu-transfer-www-$RELEASE_VER --key=${{secrets.PINATA_API_JWT}} | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
-              IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".IpfsHash")
+              ipfs-api pin ./build/ipfs saifu-transfer-www-$RELEASE_VER --key=${{secrets.PINATA_API_JWT}} --verbose=true | tee -a ./ipfs-pin.log || echo "ERROR: Failed to pin web app"
+              IPFS_HASH=$(cat ./ipfs-pin.log | tail -n 1 | bash-utils jsonParse ".hash")
               echo "IPFS_HASH=$IPFS_HASH" >> ./bin/public-envs.sh
               echo "INFO: Updating release file"
               touch ./RELEASE.md
@@ -272,20 +272,22 @@ jobs:
           - name: Comment PR's with IPFS
             # ref.: https://github.com/actions-cool/maintain-one-comment, v2.0.2
             uses: actions-cool/maintain-one-comment@cc0daaf4db77952f0b631bb2c1e169813d78a7fd
-            if: github.event_name == 'pull_request' 
+            if: github.event_name == 'pull_request' &&
+              ( startsWith(env.DESTINATION_BRANCH, 'v') && contains(env.DESTINATION_BRANCH, '.') ) &&
+              ( !startsWith(env.SOURCE_BRANCH, 'feature') && !startsWith(env.SOURCE_BRANCH, 'bugfix') )
             with:
               token: ${{ secrets.GITHUB_TOKEN }}
               update-mode: replace
               body: |
-                Web app was deployed to IPFS:
-
-                * Private Gateway: [ipfs.kira.network/ipfs/${{env.IPFS_HASH}}](https://ipfs.kira.network/ipfs/${{env.IPFS_HASH}}/index.html)
-
-                * Public Gateway: [ipfs.io/ipfs/${{env.IPFS_HASH}}](https://ipfs.io/ipfs/${{env.IPFS_HASH}}/index.html)
+                Web app was deployed to IPFS: ```CIDv1:{{env.IPFS_HASH}}```
+                * Private Gateway: [ipfs.kira.network](https://ipfs.kira.network/ipfs/${{env.IPFS_HASH}}/index.html)
+                * Public Gateway: [ipfs.io](https://ipfs.io/ipfs/${{env.IPFS_HASH}}/index.html)
           - name: Add IPFS published label
             # ref.: https://github.com/andymckay/labeler, v1.0.4
             uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
-            if: github.event_name == 'pull_request' 
+            if: github.event_name == 'pull_request' &&
+              ( startsWith(env.DESTINATION_BRANCH, 'v') && contains(env.DESTINATION_BRANCH, '.') ) &&
+              ( !startsWith(env.SOURCE_BRANCH, 'feature') && !startsWith(env.SOURCE_BRANCH, 'bugfix') )
             with:
               token: ${{ secrets.GITHUB_TOKEN }}
               add-labels: "ipfs-published"
